### ISSUE TITLE
Error when installing with pip and pipenv

### ISSUE THREAD

**Issue by Mec-iS** [thomaxxl/safrs#10]
Trying to install the package using `pipenv` with `pipenv install safrs` or the same with `pip`, this ertror message is displayed:
```
Collecting safrs
  Downloading https://files.pythonhosted.org/packages/00/21/d6b45459525d75a2a314c35ca01005f509a60ef0edf6124a72abca06cdca/safrs-1.0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-egxf1ylx/safrs/setup.py", line 17, in <module>
        long_description=open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by thomaxxl** [comment]
Hi,

can you try with safrs==1.0.16 please?

Regards,
Thomas

**Comment by Mec-iS** [comment]
Hi,
Yeah, specifying the version works.
Thanks.
