### ISSUE TITLE
Hybrid attributes

### ISSUE THREAD

**Issue by patvdleer** [thomaxxl/safrs#30]
Unable to use hybrid properties, regular properties do work

https://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html

```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = init(get_config())
  File "/home/patrick/PycharmProjects/ebookhub-backend/eBookHub/__init__.py", line 47, in init
    configure_blueprints(app)
  File "/home/patrick/PycharmProjects/ebookhub-backend/eBookHub/__init__.py", line 56, in configure_blueprints
    create_api(app)
  File "/home/patrick/PycharmProjects/ebookhub-backend/eBookHub/__init__.py", line 74, in create_api
    api.expose_object(BookEditionFile)
  File "/home/patrick/PycharmProjects/ebookhub-backend/venv/lib/python3.6/site-packages/safrs/_api.py", line 85, in expose_object
    self.expose_methods(url_prefix, tags=tags)
  File "/home/patrick/PycharmProjects/ebookhub-backend/venv/lib/python3.6/site-packages/safrs/_api.py", line 130, in expose_methods
    api_methods = safrs_object.get_jsonapi_rpc_methods()
  File "/home/patrick/PycharmProjects/ebookhub-backend/venv/lib/python3.6/site-packages/safrs/db.py", line 626, in get_documented_api_methods
    for name, method in inspect.getmembers(cls):
  File "/usr/lib/python3.6/inspect.py", line 342, in getmembers
    value = getattr(object, key)
  File "/home/patrick/PycharmProjects/ebookhub-backend/venv/lib/python3.6/site-packages/sqlalchemy/ext/hybrid.py", line 867, in __get__
    return self._expr_comparator(owner)
  File "/home/patrick/PycharmProjects/ebookhub-backend/venv/lib/python3.6/site-packages/sqlalchemy/ext/hybrid.py", line 1066, in expr_comparator
    owner, self.__name__, self, comparator(owner),
  File "/home/patrick/PycharmProjects/ebookhub-backend/venv/lib/python3.6/site-packages/sqlalchemy/ext/hybrid.py", line 1055, in _expr
    return ExprComparator(cls, expr(cls), self)
  File "/home/patrick/PycharmProjects/ebookhub-backend/eBookHub/models/core.py", line 148, in get_path
    return os.path.join(get_temp_path(), self.filename)
  File "/usr/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'InstrumentedAttribute'
```

```python
class BookEditionFile(Model):

    ...

    _result = db.Column(db.Text)
    
    ...

    @hybrid_property
    def result(self):
        if self._result:
            return json.loads(self._result)
        return None

    @result.setter
    def result(self, value):
        self._result = json.dumps(value)
```

**Comment by thomaxxl** [comment]
Hi,

this seems to be related to the json funcs used, following works:
```python

    _result = db.Column(db.Text)

    @hybrid_property
    def result(self):
        if self._result:
            return self._result
        return None

    @result.setter
    def result(self, value):
        self._result = value
```

maybe you can use a custom sqla Column type, eg. JSONType from https://github.com/thomaxxl/safrs/blob/master/safrs/safrs_types.py  .

I'll check again later.

**Comment by thomaxxl** [comment]
lol,

for some weird reason, simple calling self.__self__ resolves this issue (i was going to dispatch result() depending on whether it was called on class or instance level using self.__self__)

```python
    _result = db.Column(db.Text)

    @hybrid_property
    def result(self):
        if self._result:
            self.__self__
            return json.loads(self._result)
        return None

    @result.setter
    def result(self, value):
        self._result = json.dumps(value)
```

**Comment by thomaxxl** [comment]
Hi,

are you sure you want to use the hybrid_property. I guess you want to store json in the column, which can be implemented like this:

```python
class JSONType(PickleType):
    impl = BLOB

class Test(SAFRSBase, db.Model):
    result = db.Column(JSONType)

```

You'll need the last commit though because I introduced a bug in the attribute parsing for custom types. Also, pickling user-supplied input can be unsafe and I don't know how sqlalchemy's pickletype handles this.

**Comment by patvdleer** [comment]
Damn, Sunday morning 9:30? that's dedication!

I removed it for now, simple regular property will suffice.

I will be implementing it later on but more in the lines of JSONB compatible with the latest Postgres version.

```python
import json

from sqlalchemy import types, TypeDecorator
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql import sqltypes
from sqlalchemy.sql.functions import FunctionElement


class SqliteJsonElement(FunctionElement):
    type = types.Text()
    name = "JsonElement"

    @property
    def astext(self):
        return self


@compiles(SqliteJsonElement)
def compileSqliteJsonElement(element, compiler, **kw):
    return "jsonExtract(%s)" % compiler.process(element.clauses)


class SqliteJson(TypeDecorator):
    impl = types.Text

    def process_bind_param(self, value, dialect):
        if isinstance(value, tuple) and len(value) == 1:
            value = value[0]
        return json.dumps(value or {})

    def process_result_value(self, value, dialect):
        if value is None:
            return {}
        return json.loads(value)

    class comparator_factory(sqltypes.Concatenable.Comparator):
        def __getitem__(self, other):
            """Get the value at a given key."""
            return SqliteJsonElement(self.expr, other)


class SqliteCompatiblePostgresOptimizedJson(TypeDecorator):
    # See: http://docs.sqlalchemy.org/en/latest/core/custom_types.html
    # impl = None
    impl = types.JSON

    def load_dialect_impl(self, dialect):
        dialectTypeMap = {
            'sqlite': SqliteJson,
            'postgresql': JSONB
        }

        self.impl = dialect.type_descriptor(dialectTypeMap[dialect.name])
        return self.impl

    def process_bind_param(self, value, dialect):
        return value

    def process_result_value(self, value, dialect):
        # Todo: refactor
        if isinstance(value, tuple) and len(value) == 1:
            value = value[0]
        if isinstance(value, list) and len(value) == 1:
            value = value[0]
        if isinstance(value, dict) and len(value.keys()) == 1 and "meta" in value.keys():
            value = value["meta"]
        return value

    @property
    def comparator_factory(self):
        """express comparison behavior in terms of the base type"""
        return self.impl.comparator_factory
```
