### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by wiwengweng** [thomaxxl/safrs#48]
when I change sqlite uri to the following

````
    app.config.update(SQLALCHEMY_DATABASE_URI="sqlite:///test.db", DEBUG=True)

````

start demo_relationshio.py, I got a error:

````
D:\Python36\python3.exe D:/PycharmProjects/safrs/examples/demo_relationship.py
D:\Python36\lib\site-packages\flask_sqlalchemy\__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-09-27 17:10:28,217] _api:156 INFO: Exposing method User.send_mail on /Users/send_mail, endpoint: api.Users.send_mail
[2019-09-27 17:10:28,228] swagger_doc:380 DEBUG: no documentation for "<function SAFRSRestAPI.delete at 0x0000024D214F36A8>" 
[2019-09-27 17:10:28,239] _api:103 INFO: Exposing User on /Users/, endpoint: api.User
[2019-09-27 17:10:28,240] _api:111 INFO: Exposing Users instances on /Users/<string:UserId>/, endpoint: api.UserId
[2019-09-27 17:10:28,266] _api:217 INFO: Exposing relationship books on /Users/<string:UserId>/books, endpoint: /Users/<string:UserId>/api.books
[2019-09-27 17:10:28,269] _api:241 INFO: Exposing User relationship books on /Users/<string:UserId>/books/<string:BookId>, endpoint: /Users/<string:UserId>/api.booksId
[2019-09-27 17:10:28,283] swagger_doc:380 DEBUG: no documentation for "<function SAFRSRestAPI.delete at 0x0000024D214F36A8>" 
[2019-09-27 17:10:28,296] _api:103 INFO: Exposing Book on /Books/, endpoint: api.Book
[2019-09-27 17:10:28,298] _api:111 INFO: Exposing Books instances on /Books/<string:BookId>/, endpoint: api.BookId
[2019-09-27 17:10:28,338] _api:217 INFO: Exposing relationship user on /Books/<string:BookId>/user, endpoint: /Books/<string:BookId>/api.user
[2019-09-27 17:10:28,340] _api:241 INFO: Exposing Book relationship user on /Books/<string:BookId>/user/<string:UserId>, endpoint: /Books/<string:BookId>/api.userId
Starting API: http://localhost:5000
 * Serving Flask app "SAFRS Demo Application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
D:\Python36\lib\site-packages\flask_sqlalchemy\__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-09-27 17:10:35,801] errors:69 ERROR: Generic Error: (sqlite3.OperationalError) database is locked [SQL: 'INSERT INTO "Users" (id, name, email) VALUES (?, ?, ?)'] [parameters: ('f3899d67-f1f5-4954-a7d8-31c8b131bfab', 'thomas', 'em@il')] (Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PycharmProjects\safrs\safrs\db.py", line 152, in __init__
    safrs.DB.session.commit()
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 954, in commit
    self.transaction.commit()
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 467, in commit
    self._prepare_impl()
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 447, in _prepare_impl
    self.session.flush()
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2313, in flush
    self._flush(objects)
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "D:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
    raise value
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2404, in _flush
    flush_context.execute()
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 395, in execute
    rec.execute(self)
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 560, in execute
    uow
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 836, in _emit_insert_statements
    execute(statement, multiparams)
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "D:\Python36\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "D:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "D:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "D:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'INSERT INTO "Users" (id, name, email) VALUES (?, ?, ?)'] [parameters: ('f3899d67-f1f5-4954-a7d8-31c8b131bfab', 'thomas', 'em@il')] (Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/PycharmProjects/safrs/examples/demo_relationship.py", line 78, in <module>
    user = User(name="thomas", email="em@il")
  File "<string>", line 4, in __init__
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\state.py", line 424, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "D:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
    raise value
  File "D:\Python36\lib\site-packages\sqlalchemy\orm\state.py", line 421, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\PycharmProjects\safrs\safrs\db.py", line 155, in __init__
    raise GenericError(exc)
safrs.errors.GenericError
````

**Comment by wiwengweng** [comment]
solved by commented db create script:

````
        # user = User(name="thomas", email="em@il")
        # book = Book(name="test_book")
        # user.books.append(book)
````
