### ISSUE TITLE
pypi version safrs==1.0.10 does not support pip 10, master code does

### ISSUE THREAD

**Issue by DennyWeinberg** [thomaxxl/safrs#5]
```
Collecting safrs==1.0.10 (from x)
  Using cached https://files.pythonhosted.org/packages/7b/05/abc1846dcd495d08c734c61244077f596c39d9036af47304e3f24777f7dd/safrs-1.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\denny\AppData\Local\Temp\pip-install-u55tif5y\safrs\setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------

```

**Comment by thomaxxl** [comment]
Thanks for bringing this to my attention.
I've messed up the versioning now though, can you try --upgrade to .11 ?

**Comment by DennyWeinberg** [comment]
Yeah this works. `safrs==1.0.11`
