### ISSUE TITLE
demo_jwt.py  -- TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by NexPlex** [thomaxxl/safrs#61]
When I run examples\authentication\demo_jwt.py I get this error: **TypeError: 'module' object is not callable** How do I resolve this error?

```python 

Traceback (most recent call last):
  File "C:\Sites\safrs2\safrs\_api.py", line 468, in api_decorator
    decorated_method = swagger_decorator(decorated_method)
  File "C:\Sites\safrs2\safrs\swagger_doc.py", line 484, in swagger_doc_gen
    rel_post_schema = schema_from_object("{}_Relationship".format(class_name), {"data": data})
  File "C:\Sites\safrs2\safrs\swagger_doc.py", line 198, in schema_from_object
    properties = encode_schema(properties)
  File "C:\Sites\safrs2\safrs\swagger_doc.py", line 154, in encode_schema
    log.warning("Json encoding failed for {}, type {} ({})".format(obj, type(obj), exc))
NameError: name 'log' is not defined
[2020-04-27 12:22:37,736] _api:475 ERROR: Failed to generate documentation for <function SAFRSRestRelationshipAPI.post at 0x051731E0>
[2020-04-27 12:22:37,784] _api:474 ERROR: name 'log' is not defined
<function SAFRSRestRelationshipAPI.delete at 0x051738A0> delete
Traceback (most recent call last):
  File "C:\Sites\safrs2\safrs\swagger_doc.py", line 152, in encode_schema
    result = json.loads(json.dumps(obj, cls=flask.current_app.json_encoder))
  File "c:\users\chris\appdata\local\programs\python\python36-32\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: 'module' object is not callable
```

**Comment by thomaxxl** [comment]
The auth examples were not adapted to recent changes. I updated the jwt example so it runs now.
There's still something wrong with the swagger: it's not sending the Authorization header. Using curl on the cli does work:

```bash
curl -X GET "http://192.168.235.136:5000/Users/?include=items&fields%5BUser%5D=username&page%5Boffset%5D=0&page%5Blimit%5D=10&sort=username%2Cid" -H "accept: application/vnd.api+json" -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODgwNjUxMzgsIm5iZiI6MTU4ODA2NTEzOCwianRpIjoiZTVkNmFlZDktODlhNC00Zjc0LTg4MmMtYjU5ZjY0ZDczYzg2IiwiZXhwIjoxNTg4MDY2MDM4LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.AnM8RF1ewnr467qLlTVgwMfiaETLFHtI4igGuQbVJsY"
```

**Comment by thomaxxl** [comment]
Can you try the latest examples/demo_jwt.py commit? I've modified the swagger.

I still have to double check everything tho.

**Comment by NexPlex** [comment]
Hi, Thomas, everything seems to work correctly now. Thank you.
